repo = (Pathname(__dir__) + "../tmp/rbs/gem_rbs_collection/gems").to_s

target :protobuf_gem do
  check "protobuf_gem_example.rb", "protobuf-gem"
  signature "protobuf-gem"

  repo_path repo
  library "protobuf"
end
