D = Steep::Diagnostic

target :lib do
  collection_config "../rbs_collection.yaml"

  signature "protobuf-gem"
  signature "../vendor/gem_rbs_collection/gems/protobuf"
  check "protobuf_gem_example.rb"

  configure_code_diagnostics do |hash|
    hash[D::Ruby::FallbackAny] = :hint
    hash[D::Ruby::MethodDefinitionMissing] = :hint
    hash[D::Ruby::UnknownConstant] = :information
  end
end
