#!/usr/bin/env ruby

$LOAD_PATH << File.join(__dir__, "../lib")

require "rbs_protobuf"

backend = ENV["RBS_PROTOBUF_BACKEND"]
unless backend
  STDERR.puts "🚨🚨🚨 protoc-gen-rbs requires RBS_PROTOBUF_BACKEND environment variable. 🚨🚨🚨"
  STDERR.puts "  Possible options:"
  STDERR.puts "    RBS_PROTOBUF_BACKEND=protobuf         (for protobuf gem)"
  STDERR.puts "    RBS_PROTOBUF_BACKEND=google-protobuf  (for google-protobuf gem)"
  exit 1
end

input = Google::Protobuf::Compiler::CodeGeneratorRequest.decode(STDIN.read)

translator = case backend
             when "protobuf"
               upcase_enum = ENV.key?("PB_UPCASE_ENUMS")
               no_nested_namespace = ENV.key?("RBS_PROTOBUF_NO_NESTED_NAMESPACE")
               extension = case ENV["RBS_PROTOBUF_EXTENSION"]
                           when "false"
                             false
                           when nil
                             nil
                           when "print"
                             :print
                           else
                             true
                           end

               RBSProtobuf::Translator::ProtobufGem.new(
                 input,
                 upcase_enum: upcase_enum,
                 nested_namespace: !no_nested_namespace,
                 extension: extension
               )
             when "google-protobuf"
               raise NotImplementedError
             end

translator.generate_rbs!

response = translator.response
print Google::Protobuf::Compiler::CodeGeneratorResponse.encode(response)
