#!/usr/bin/env ruby

$LOAD_PATH << File.join(__dir__, "../lib")

require "rbs_protobuf"

input = Google::Protobuf::Compiler::CodeGeneratorRequest.decode(STDIN.read)
response = RBSProtobuf::Translator.new(input).response
print Google::Protobuf::Compiler::CodeGeneratorResponse.encode(response)
